-- ============================================================================
-- Migration: Create Core Tables (flashcards, generations, generation_error_logs)
-- Author: AI Assistant
-- Date: 2025-11-04
-- Description: Creates the core tables for the 10x Cards MVP application.
--              This includes flashcards storage, AI generation metrics,
--              and error logging capabilities.
-- Tables Created:
--   - generations: Tracks AI flashcard generation sessions and metrics
--   - flashcards: Stores user flashcards (manual and AI-generated)
--   - generation_error_logs: Logs errors during AI generation process
-- Notes:
--   - Tables are created in dependency order (generations before flashcards)
--   - RLS is enabled on all tables but policies are defined in separate migration
--   - All timestamps use timestamptz for timezone awareness
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: generations
-- Purpose: Stores metrics and metadata about AI flashcard generation sessions
-- Dependencies: auth.users (Supabase Auth)
-- RLS: Enabled (policies defined separately)
-- ----------------------------------------------------------------------------
create table if not exists public.generations (
  -- Primary key: auto-incrementing bigint for efficient indexing
  id bigint primary key generated always as identity,
  
  -- Foreign key to auth.users: tracks which user performed the generation
  -- ON DELETE SET NULL preserves metrics even after user deletion
  user_id uuid references auth.users(id) on delete set null,
  
  -- Model name used for generation (e.g., 'gpt-4', 'claude-3-opus')
  -- varchar(100) accommodates long model version names
  model varchar(100) not null,
  
  -- Count of flashcards generated by AI in this session
  -- Must be positive (at least 1 card generated)
  generated_count integer not null check (generated_count > 0),
  
  -- Count of flashcards accepted without any edits
  -- Nullable until user reviews the generated cards
  -- Used to measure AI generation quality
  accepted_unedited_count integer check (accepted_unedited_count >= 0),
  
  -- Count of flashcards accepted after user edits
  -- Nullable until user reviews the generated cards
  -- Used to measure need for human refinement
  accepted_edited_count integer check (accepted_edited_count >= 0),
  
  -- SHA-256 hash of source text used for generation
  -- varchar(64) matches SHA-256 hex output length
  -- Enables duplicate detection and analysis without storing full text
  source_text_hash varchar(64) not null,
  
  -- Length of source text in characters
  -- Used to analyze correlation between input length and generation quality
  source_text_length integer not null check (source_text_length > 0),
  
  -- Generation duration in milliseconds
  -- Used for performance monitoring and API response time analysis
  generation_duration integer not null check (generation_duration >= 0),
  
  -- Timestamp when generation session was created
  created_at timestamptz not null default now(),
  
  -- Timestamp of last update (e.g., when acceptance counts are updated)
  updated_at timestamptz not null default now()
);

-- Enable RLS on generations table
-- Note: This table is for analytics only, no user-facing access
-- Policies will be defined in separate migration if needed
alter table public.generations enable row level security;

-- Add comment to table for documentation
comment on table public.generations is 'Stores metrics and metadata about AI flashcard generation sessions for analytics and quality monitoring';

-- ----------------------------------------------------------------------------
-- Table: flashcards
-- Purpose: Stores all user flashcards (manually created and AI-generated)
-- Dependencies: auth.users, generations
-- RLS: Enabled (policies defined separately)
-- ----------------------------------------------------------------------------
create table if not exists public.flashcards (
  -- Primary key: auto-incrementing bigint for efficient indexing and sorting
  id bigint primary key generated always as identity,
  
  -- Foreign key to auth.users: identifies the flashcard owner
  -- ON DELETE CASCADE ensures GDPR compliance (user deletion removes all data)
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- Front side of flashcard (concept/question)
  -- varchar(5000) limits storage while maintaining flexibility
  -- Must not be empty string
  front varchar(5000) not null check (length(front) > 0),
  
  -- Back side of flashcard (definition/answer)
  -- varchar(5000) limits storage while maintaining flexibility
  -- Must not be empty string
  back varchar(5000) not null check (length(back) > 0),
  
  -- Source of flashcard creation: 'manual' (user-created) or 'ai' (generated)
  -- varchar(20) allows for future extension to other sources
  source varchar(20) not null check (source in ('manual', 'ai')),
  
  -- Foreign key to generations: links AI-generated cards to generation session
  -- NULL for manually created flashcards
  -- ON DELETE SET NULL preserves flashcards even if generation record is deleted
  generation_id bigint references public.generations(id) on delete set null,
  
  -- Timestamp when flashcard was created
  created_at timestamptz not null default now(),
  
  -- Timestamp of last modification
  -- Useful for tracking edits and potential future sync features
  updated_at timestamptz not null default now()
);

-- Enable RLS on flashcards table
-- Users should only access their own flashcards
-- Policies will be defined in separate migration
alter table public.flashcards enable row level security;

-- Add comment to table for documentation
comment on table public.flashcards is 'Stores all user flashcards including manually created and AI-generated cards';

-- ----------------------------------------------------------------------------
-- Table: generation_error_logs
-- Purpose: Logs errors occurring during AI flashcard generation
-- Dependencies: auth.users
-- RLS: Enabled (policies defined separately)
-- Notes: This table is for debugging and monitoring only, no user-facing access
-- ----------------------------------------------------------------------------
create table if not exists public.generation_error_logs (
  -- Primary key: auto-incrementing bigint for efficient indexing
  id bigint primary key generated always as identity,
  
  -- Foreign key to auth.users: identifies user who encountered the error
  -- NULL for system-level errors not tied to specific user
  -- ON DELETE SET NULL preserves error logs for analysis after user deletion
  user_id uuid references auth.users(id) on delete set null,
  
  -- Model name that was being used when error occurred
  -- Nullable as error may occur before model selection
  model varchar(100),
  
  -- SHA-256 hash of source text that caused the error
  -- Nullable as error may occur before text processing
  -- Helps identify problematic input patterns
  source_text_hash varchar(64),
  
  -- Length of source text in characters
  -- Nullable as error may occur before text processing
  -- Helps identify if text length correlates with errors
  source_text_length integer check (source_text_length is null or source_text_length > 0),
  
  -- Error code returned by API/system
  -- Nullable for errors without specific codes
  error_code varchar(50),
  
  -- Human-readable error message
  -- Required field describing what went wrong
  error_message text not null check (length(error_message) > 0),
  
  -- Timestamp when error occurred
  created_at timestamptz not null default now()
);

-- Enable RLS on generation_error_logs table
-- This table is for admin/monitoring access only
-- Policies will be defined in separate migration if needed
alter table public.generation_error_logs enable row level security;

-- Add comment to table for documentation
comment on table public.generation_error_logs is 'Logs errors during AI flashcard generation for debugging and monitoring purposes';

-- ----------------------------------------------------------------------------
-- Triggers for updated_at columns
-- Purpose: Automatically update updated_at timestamp on row modifications
-- ----------------------------------------------------------------------------

-- Create function to update updated_at timestamp
-- Security: search_path is set to empty string to prevent search path injection attacks
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Add trigger to generations table
create trigger set_updated_at
  before update on public.generations
  for each row
  execute function public.handle_updated_at();

-- Add trigger to flashcards table
create trigger set_updated_at
  before update on public.flashcards
  for each row
  execute function public.handle_updated_at();

-- Add comments to function for documentation
comment on function public.handle_updated_at() is 'Trigger function to automatically update updated_at timestamp on row modification';

